---
  deployment:
    tasks:
      - export DEPLOYPATH=/home3/xaviermi/public_html/xbot/
      - /bin/cp dist/index.html $DEPLOYPATH
      - /bin/cp dist/index.*.js $DEPLOYPATH
      - /bin/cp dist/vendors~index.*.js $DEPLOYPATH
      - /bin/cp -R dist/templates $DEPLOYPATH
